# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

!if "$(VERBOSE)" != "1"
VV=@
!endif

AS=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\ml64.exe
CC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe

LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
SH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
AR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe

z-core_AR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
z-core_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
z-core_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
z-core_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
excel_cli_AR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
excel_cli_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
excel_cli_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
excel_cli_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
z-cli_LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
z-cli_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
z-cli_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
z-cli_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe

z-core_CXXFLAGS=-nologo -MDd -std:c++17 -Isrc\core\spdlog-1.15.3\include -Isrc\core\vfspp\include -Isrc\core\vfspp\include\vfspp -Isrc\core\vfspp\vendor\miniz-cpp -DCURL_STATICLIB /EHsc -external:W0 -external:IC:\Users\wanderer\AppData\Local\.xmake\packages\l\libcurl\8.11.0\fa6dea0c4bac4bd2b472a36db1547bdc\include
z-core_CXXFLAGS=
z-core_CXXFLAGS=
z-core_ARFLAGS=-nologo -machine:x64
excel_cli_CXXFLAGS=-nologo -MDd -std:c++17 -Isrc\core\spdlog-1.15.3\include -Isrc\core\vfspp\include -Isrc\core\vfspp\include\vfspp -Isrc\core\vfspp\vendor\miniz-cpp /EHsc
excel_cli_CXXFLAGS=
excel_cli_CXXFLAGS=
excel_cli_ARFLAGS=-nologo -machine:x64
z-cli_CXXFLAGS=-nologo -MDd -std:c++17 -Isrc\core\spdlog-1.15.3\include -Isrc\core\vfspp\include -Isrc\core\vfspp\include\vfspp -Isrc\core\vfspp\vendor\miniz-cpp /EHsc
z-cli_CXXFLAGS=
z-cli_CXXFLAGS=
z-cli_LDFLAGS=-nologo -dynamicbase -nxcompat -machine:x64 -libpath:build\windows\x64\debug -libpath:C:\Users\wanderer\AppData\Local\.xmake\packages\l\libcurl\8.11.0\fa6dea0c4bac4bd2b472a36db1547bdc\lib excel_cli.lib z-core.lib libcurl.lib advapi32.lib crypt32.lib wldap32.lib winmm.lib ws2_32.lib user32.lib

default:  z-core excel_cli z-cli

all:  z-core excel_cli z-cli

.PHONY: default all  z-core excel_cli z-cli

z-core: build\windows\x64\debug\z-core.lib
build\windows\x64\debug\z-core.lib: build\.objs\z-core\windows\x64\debug\src\core\cli_core.cpp.obj
	@echo linking.debug z-core.lib
	-@mkdir build\windows\x64\debug > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\link.exe" -lib $(z-core_ARFLAGS) -out:build\windows\x64\debug\z-core.lib build\.objs\z-core\windows\x64\debug\src\core\cli_core.cpp.obj

build\.objs\z-core\windows\x64\debug\src\core\cli_core.cpp.obj: src\core\cli_core.cpp
	@echo compiling.debug src\core\cli_core.cpp
	-@mkdir build\.objs\z-core\windows\x64\debug\src\core > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(z-core_CXXFLAGS) -Fobuild\.objs\z-core\windows\x64\debug\src\core\cli_core.cpp.obj src\core\cli_core.cpp

excel_cli: build\windows\x64\debug\excel_cli.lib
build\windows\x64\debug\excel_cli.lib: build\windows\x64\debug\z-core.lib build\.objs\excel_cli\windows\x64\debug\src\excel\excel_cli.cpp.obj
	@echo linking.debug excel_cli.lib
	-@mkdir build\windows\x64\debug > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\link.exe" -lib $(excel_cli_ARFLAGS) -out:build\windows\x64\debug\excel_cli.lib build\.objs\excel_cli\windows\x64\debug\src\excel\excel_cli.cpp.obj

build\.objs\excel_cli\windows\x64\debug\src\excel\excel_cli.cpp.obj: src\excel\excel_cli.cpp
	@echo compiling.debug src\excel\excel_cli.cpp
	-@mkdir build\.objs\excel_cli\windows\x64\debug\src\excel > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(excel_cli_CXXFLAGS) -Fobuild\.objs\excel_cli\windows\x64\debug\src\excel\excel_cli.cpp.obj src\excel\excel_cli.cpp

z-cli: build\windows\x64\debug\z-cli.exe
build\windows\x64\debug\z-cli.exe: build\windows\x64\debug\z-core.lib build\windows\x64\debug\excel_cli.lib build\.objs\z-cli\windows\x64\debug\src\cli_app.cpp.obj build\.objs\z-cli\windows\x64\debug\src\main.cpp.obj build\.objs\z-cli\windows\x64\debug\src\update\update_cli.cpp.obj
	@echo linking.debug z-cli.exe
	-@mkdir build\windows\x64\debug > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\link.exe" $(z-cli_LDFLAGS) -out:build\windows\x64\debug\z-cli.exe build\.objs\z-cli\windows\x64\debug\src\cli_app.cpp.obj build\.objs\z-cli\windows\x64\debug\src\main.cpp.obj build\.objs\z-cli\windows\x64\debug\src\update\update_cli.cpp.obj

build\.objs\z-cli\windows\x64\debug\src\cli_app.cpp.obj: src\cli_app.cpp
	@echo compiling.debug src\cli_app.cpp
	-@mkdir build\.objs\z-cli\windows\x64\debug\src > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(z-cli_CXXFLAGS) -Fobuild\.objs\z-cli\windows\x64\debug\src\cli_app.cpp.obj src\cli_app.cpp

build\.objs\z-cli\windows\x64\debug\src\main.cpp.obj: src\main.cpp
	@echo compiling.debug src\main.cpp
	-@mkdir build\.objs\z-cli\windows\x64\debug\src > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(z-cli_CXXFLAGS) -Fobuild\.objs\z-cli\windows\x64\debug\src\main.cpp.obj src\main.cpp

build\.objs\z-cli\windows\x64\debug\src\update\update_cli.cpp.obj: src\update\update_cli.cpp
	@echo compiling.debug src\update\update_cli.cpp
	-@mkdir build\.objs\z-cli\windows\x64\debug\src\update > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(z-cli_CXXFLAGS) -Fobuild\.objs\z-cli\windows\x64\debug\src\update\update_cli.cpp.obj src\update\update_cli.cpp

clean:  clean_z-core clean_excel_cli clean_z-cli

clean_z-core: 
	@del /F /Q build\windows\x64\debug\z-core.lib > NUL 2>&1 || rmdir /S /Q build\windows\x64\debug\z-core.lib > NUL 2>&1
	@del /F /Q build\windows\x64\debug\z-core.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\debug\z-core.pdb > NUL 2>&1
	@del /F /Q build\.objs\z-core\windows\x64\debug\src\core\cli_core.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\z-core\windows\x64\debug\src\core\cli_core.cpp.obj > NUL 2>&1

clean_excel_cli:  clean_z-core
	@del /F /Q build\windows\x64\debug\excel_cli.lib > NUL 2>&1 || rmdir /S /Q build\windows\x64\debug\excel_cli.lib > NUL 2>&1
	@del /F /Q build\windows\x64\debug\excel_cli.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\debug\excel_cli.pdb > NUL 2>&1
	@del /F /Q build\.objs\excel_cli\windows\x64\debug\src\excel\excel_cli.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\excel_cli\windows\x64\debug\src\excel\excel_cli.cpp.obj > NUL 2>&1

clean_z-cli:  clean_z-core clean_excel_cli
	@del /F /Q build\windows\x64\debug\z-cli.exe > NUL 2>&1 || rmdir /S /Q build\windows\x64\debug\z-cli.exe > NUL 2>&1
	@del /F /Q build\windows\x64\debug\z-cli.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\debug\z-cli.pdb > NUL 2>&1
	@del /F /Q build\.objs\z-cli\windows\x64\debug\src\cli_app.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\z-cli\windows\x64\debug\src\cli_app.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\z-cli\windows\x64\debug\src\main.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\z-cli\windows\x64\debug\src\main.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\z-cli\windows\x64\debug\src\update\update_cli.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\z-cli\windows\x64\debug\src\update\update_cli.cpp.obj > NUL 2>&1

